# -*- coding: utf-8 -*-
"""TRAFFIC LIGHT DETECTION(MAIN)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bFIo2WuVDDq_KI-hyxAExxucSfPUc17Y

### **Access/Enable GPU for fast processing**
"""

import os

if 'COLAB_GPU' in os.environ:
  print("GPU is enabled !")
else:
    print("GPU is not enabled!")

"""INSTALL The YOLO-8"""

!pip install ultralytics==8.0.2

import ultralytics
ultralytics.checks()

# Commented out IPython magic to ensure Python compatibility.
# %pwd

!mkdir TrafficLightDetection

!ls

path = "/content/TrafficLightDetection"

# Commented out IPython magic to ensure Python compatibility.
# %pwd

# Commented out IPython magic to ensure Python compatibility.
import os
os.chdir("/content/TrafficLightDetection")
# %pwd

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="HEdknxxKTOdanD5UL3gR")
project = rf.workspace("sohryu").project("traffic-light-detector-ncnsz")
version = project.version(2)
dataset = version.download("yolov8")

os.chdir("/content/TrafficLightDetection/traffic-light-detector-2")

!yolo task=detect mode=train model=yolov8n.pt data=data.yaml epochs=15 imgsz=640 batch=16

!ls '/content/TrafficLightDetection/traffic-light-detector-2/runs/detect/train'

from IPython.display import Image, display

RESULT_DATA = "/content/TrafficLightDetection/traffic-light-detector-2/runs/detect/train"
image_path = f"{RESULT_DATA}/confusion_matrix.png"

# Display the image
display(Image(filename=image_path))

from IPython.display import Image, display

RESULT_DATA = "/content/TrafficLightDetection/traffic-light-detector-2/runs/detect/train"
image_path = f"{RESULT_DATA}/F1_curve.png"

# Display the image
display(Image(filename=image_path))

from IPython.display import Image, display

RESULT_DATA = "/content/TrafficLightDetection/traffic-light-detector-2/runs/detect/train"
image_path = f"{RESULT_DATA}/P_curve.png"

# Display the image
display(Image(filename=image_path))

from IPython.display import Image, display

RESULT_DATA = "/content/TrafficLightDetection/traffic-light-detector-2/runs/detect/train"
image_path = f"{RESULT_DATA}/PR_curve.png"

# Display the image
display(Image(filename=image_path))

from IPython.display import Image, display

RESULT_DATA = "/content/TrafficLightDetection/traffic-light-detector-2/runs/detect/train"
image_path = f"{RESULT_DATA}/R_curve.png"

# Display the image
display(Image(filename=image_path))

from IPython.display import Image, display

RESULT_DATA = "/content/TrafficLightDetection/traffic-light-detector-2/runs/detect/train"
image_path = f"{RESULT_DATA}/results.png"

# Display the image
display(Image(filename=image_path))

from IPython.display import Image, display

RESULT_DATA = "/content/TrafficLightDetection/traffic-light-detector-2/runs/detect/train"
image_path = f"{RESULT_DATA}/results.png"

# Display the image
display(Image(filename=image_path))

import pandas as pd

RESULT_DATA = "/content/TrafficLightDetection/traffic-light-detector-2/runs/detect/train"
csv_file_path = f'{RESULT_DATA}/results.csv'

df = pd.read_csv(csv_file_path)

# Print the first 5 rows of the DataFrame
print(df.head(5))

import pandas as pd

RESULT_DATA = "/content/TrafficLightDetection/traffic-light-detector-2/runs/detect/train"
csv_file_path = f'{RESULT_DATA}/results.csv'

df = pd.read_csv(csv_file_path)

# Print the first 5 rows of the DataFrame
print(df.tail(1))

WEIGHTS_PATH = "/content/TrafficLightDetection/traffic-light-detector-2/runs/detect/train/weights"

!yolo task=detect mode=predict model={WEIGHTS_PATH}/best.pt conf=0.25 source={path}/test/images save=True

# Commented out IPython magic to ensure Python compatibility.
# %pwd

os.chdir("/content")

# Commented out IPython magic to ensure Python compatibility.
# %pwd

!mkdir MANUALL_TEST

os.chdir("/content/MANUALL_TEST")

URL = "https://drive.google.com/file/d/1yA59gmTyWkmqA4zb_LtLZJ9kf5fTkF8l/view?usp=sharing"

id = '1yA59gmTyWkmqA4zb_LtLZJ9kf5fTkF8l'

!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1yA59gmTyWkmqA4zb_LtLZJ9kf5fTkF8l' -O 'inputvedio1.mp4'

URL = "https://drive.google.com/file/d/1TXNWc72yD7ogdxlEl8mv6Piu4VeImQLi/view?usp=sharing"

id = '1TXNWc72yD7ogdxlEl8mv6Piu4VeImQLi'

!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1TXNWc72yD7ogdxlEl8mv6Piu4VeImQLi' -input_pic.jpeg

WEIGHTS_PATH = "/content/TrafficLightDetection/traffic-light-detector-2/runs/detect/train/weights"

!yolo task=detect mode=predict model={WEIGHTS_PATH}/best.pt conf=0.25 source='inputvedio1.mp4' save=True

from google.colab import files

files.download("/content/MANUALL_TEST/runs/detect/predict4/inputvedio1.mp4")